Add flat fee discount command line parameter (gnosis/gp-v2-services#1348)
This PR adds a command line parameter for specifying a flat fee discount denominated in Eth. Note that the the `orderbook` executable will panic for any other value than `0` because it currently isn't supported. The idea behind this PR is just to make a small change to work up flat fee discounts and keep future PRs shorter.

### Test Plan

No real logic changes. Can check that the parameter defaults to 0 and panics for any other value than 0:
```
$ cargo run -p orderbook
... # Everything OK
$ cargo run -p orderbook -- --fee-discount 42
...
2021-11-04T13:30:05.282Z ERROR shared::tracing: thread 'main' panicked at 'non-0 fee discount currently not supported', orderbook/src/fee.rs:198:9:
thread 'main' panicked at 'non-0 fee discount currently not supported', orderbook/src/fee.rs:198:9
```