Better error messages when failing to retrieve Balancer factory (#1517)
Small QOL PR to make panic debugging quicker.

### Test Plan

```
$ export NODE_URL='an xdai node'
$ export BALANCER_FACTORIES='Weighted'
$ export BASELINE_SOURCES='BalancerV2'
$ cargo  run --bin orderbook -- 
[...]
2023-05-18T10:58:28.526Z ERROR shared::tracing: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Cannot retrieve Balancer factory BalancerV2WeightedPoolFactory

Caused by:
    could not find deployed contract for network 100', /home/fedgiac/code/gnosis/services/crates/orderbook/src/run.rs:266:72
```