Balancer V2 Liquidity Configuration in the Driver (#1698)
☝️ 

This PR just introduces Balancer V2 liquidity in the driver.

### Test Plan

Run the driver with Balancer V2 liquidity and watch it crash (with the
configuration!):

```
thread 'main' panicked at 'not yet implemented: Balancer V2 liquidity fetcher not implemented: [BalancerV2 { vault: ContractAddress(0xba12222222228d8ba445958a75a0704d566bf2c8), weighted: [ContractAddress(0x8e9aa87e45e92bad84d5f8dd1bff34fb92637de9), ContractAddress(0x5dd94da3644ddd055fcf6b3e1aa310bb7801eb8b), ContractAddress(0x897888115ada5773e02aa29f775430bfb5f34c51), ContractAddress(0xa5bf2ddf098bb0ef6d120c98217dd6b141c74ee0)], stable: [ContractAddress(0xc66ba2b6595d3613ccab350c886ace23866ede24), ContractAddress(0x8df6efec5547e31b0eb7d1291b511ff8a2bf987c)], liquidity_bootstrapping: [ContractAddress(0x751a0bc0e3f75b38e01cf25bfce7ff36de1c87de), ContractAddress(0x0f3e0c4218b7b0108a3643cfe9d3ec0d4f57c54e)] }]', /Users/nlordell/Developer/cowprotocol/services/crates/driver/src/boundary/liquidity/mod.rs:84:13
```