Configure Relative and Absolute Slippage for all Solvers (#595)
Fixes #578 

This PR adds command line configuration options for configuring relative and absolute slippage for all solvers. With this change, we can have an absolute cap on the negative slippage for all internal solvers can incur in a settlement, limiting potential solver losses.

Note that, in order to make slippage configuration more succinct, I modified how slippage configuration works. There are now only two flags `--relative-slippage-bps` and `--absolute-slippage-in-native-token`. These flags can specify values as:
```
${global_value}(,${solver_kind}=${solver_value})*
```

This allows us to specify a global value that applies to all solvers (with `~` to represent "default" - so 10 BPS and no absolute cap) as well as specific solver override values. This means that our current slippage configuration can be represented as:
```
--relative-slippage-bps "10,zeroex=30,oneinch=30,paraswap=30"
--absolute-slippage-in-native-token "~,oneinch=0.001"
```

Additionally, with the recent crate updates, the CLI arguments started generating a panic with:
```
% cargo run -p solver
    Finished dev [unoptimized + debuginfo] target(s) in 8.30s
     Running `target/debug/solver`
thread 'main' panicked at 'Command solver: Argument group name must be unique

	'Arguments' is already in use', /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.0.4/src/builder/debug_asserts.rs:284:9
```

Note that this **does not** affect release, which is one of the reasons why it snuck by. The workaround is very easy, so I included it here.

### Test Plan

The compiler makes sure I didn't forget to initialize the `SlippageCalculator` anywhere. Check that solvers are initialized with expected values:

```
% cargo run -p solver -- --relative-slippage-bps 30,paraswap=40 --absolute-slippage-in-native-token ~,zeroex=0.01,oneinch=0.0042 --solvers OneInch,ZeroEx,ParaSwap,Baseline
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/solver --relative-slippage-bps 30,paraswap=40 --absolute-slippage-in-native-token '~,zeroex=0.01,oneinch=0.0042' --solvers OneInch,ZeroEx,ParaSwap,Baseline`
...
relative_slippage_bps: 30,Paraswap=40
absolute_slippage_in_native_token: ~,OneInch=0.0042,ZeroEx=0.01
...
2022-09-29T16:25:17.263Z DEBUG solver::solver: configured slippage solver=OneInch slippage=SlippageCalculator { relative: Ratio { numer: 3, denom: 1000 }, absolute: Some(4199999999999999) }
2022-09-29T16:25:17.263Z DEBUG solver::solver: configured slippage solver=ZeroEx slippage=SlippageCalculator { relative: Ratio { numer: 3, denom: 1000 }, absolute: Some(10000000000000000) }
2022-09-29T16:25:17.264Z DEBUG solver::solver: configured slippage solver=Paraswap slippage=SlippageCalculator { relative: Ratio { numer: 1, denom: 250 }, absolute: None }
2022-09-29T16:25:17.264Z DEBUG solver::solver: configured slippage solver=Baseline slippage=SlippageCalculator { relative: Ratio { numer: 3, denom: 1000 }, absolute: None }
...
```

### Release Notes

This changes how we configure slippage:
- [x] Refactor slippage configuration for our deployments