Fix panic for liquidity orders buying Eth (#327)
Fixes observed naive solver panics.

We have special encoding semantics for:
- Liquidity orders
- Ether buy orders (i.e. buy orders that use the special `0xe...` marker address.

Specifically, for liquidity orders, we add additional clearing price entries for their `buy_token` to ensure that they always get exactly their limit price when trading.

For Ether buy orders, we change their `buy_token` to the wrapped native token (WETH on mainnet for example) before sending `LiquidityOrder` instances to individual solvers. When these orders get added to the settlement, we add an extra clearing price for `0xe...` that matches exactly the price of the wrapped native token (e.g. WETH). In the code we call this a "token equivalency".

However, when adding liquidity Ether buy orders, **we do not add a "token equivalency" between `0xe...` and the native wrapped token**. This leads to a missing `buy_token` price for liquidity Ether buy orders when we are checking the settlement is valid in the Naive solver. Note that when encoding the liquidity Ether buy order we already add a `0xe...` token price matching its buy amount, so the settlement should actually be valid.

The solution is simple: since we already know that the orders in the settlement trade over the same token pair and this token pair already converts `0xe...` to native wrapped token, we can just use the token that isn't the order's sell token as the buy token (instead of the order's actual buy token).

### Test Plan

Added a unit test. You can also verify that the added test was indeed causing the panic by:
```
% git checkout main -- crates/solver/src/solver/naive_solver/multi_order_solver.rs 
% cargo test -p solver -- works_with_eth_liquidity_orders
   Compiling solver v0.1.0 (/Users/nlordell/Developer/cowprotocol/services/crates/solver)
    Finished test [unoptimized + debuginfo] target(s) in 6.90s
     Running unittests src/lib.rs (target/debug/deps/solver-8a3820337d63a133)

running 1 test
test solver::naive_solver::tests::works_with_eth_liquidity_orders ... FAILED

failures:

---- solver::naive_solver::tests::works_with_eth_liquidity_orders stdout ----
thread 'solver::naive_solver::tests::works_with_eth_liquidity_orders' panicked at 'Solution should contain clearing price for buy token', crates/solver/src/solver/naive_solver/multi_order_solver.rs:286:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    solver::naive_solver::tests::works_with_eth_liquidity_orders

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 165 filtered out; finished in 0.01s

error: test failed, to rerun pass '-p solver --lib'
```